// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/ipc/message.proto

package ipc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Request_AdvanceSplit
	//	*Request_ResetActiveRun
	//	*Request_MoveActiveSplitBack
	Payload       isRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_pkg_ipc_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_message_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Request) GetPayload() isRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Request) GetAdvanceSplit() *AdvanceSplit {
	if x != nil {
		if x, ok := x.Payload.(*Request_AdvanceSplit); ok {
			return x.AdvanceSplit
		}
	}
	return nil
}

func (x *Request) GetResetActiveRun() *ResetActiveRun {
	if x != nil {
		if x, ok := x.Payload.(*Request_ResetActiveRun); ok {
			return x.ResetActiveRun
		}
	}
	return nil
}

func (x *Request) GetMoveActiveSplitBack() *MoveActiveSplitBack {
	if x != nil {
		if x, ok := x.Payload.(*Request_MoveActiveSplitBack); ok {
			return x.MoveActiveSplitBack
		}
	}
	return nil
}

type isRequest_Payload interface {
	isRequest_Payload()
}

type Request_AdvanceSplit struct {
	AdvanceSplit *AdvanceSplit `protobuf:"bytes,2,opt,name=advance_split,json=advanceSplit,proto3,oneof"`
}

type Request_ResetActiveRun struct {
	ResetActiveRun *ResetActiveRun `protobuf:"bytes,3,opt,name=reset_active_run,json=resetActiveRun,proto3,oneof"`
}

type Request_MoveActiveSplitBack struct {
	MoveActiveSplitBack *MoveActiveSplitBack `protobuf:"bytes,4,opt,name=move_active_split_back,json=moveActiveSplitBack,proto3,oneof"`
}

func (*Request_AdvanceSplit) isRequest_Payload() {}

func (*Request_ResetActiveRun) isRequest_Payload() {}

func (*Request_MoveActiveSplitBack) isRequest_Payload() {}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Response_AdvanceSplitResult
	//	*Response_ResetActiveRunResult
	//	*Response_MoveActiveSplitBackResult
	Payload       isResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_pkg_ipc_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_message_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Response) GetPayload() isResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Response) GetAdvanceSplitResult() *AdvanceSplitResult {
	if x != nil {
		if x, ok := x.Payload.(*Response_AdvanceSplitResult); ok {
			return x.AdvanceSplitResult
		}
	}
	return nil
}

func (x *Response) GetResetActiveRunResult() *ResetActiveRunResult {
	if x != nil {
		if x, ok := x.Payload.(*Response_ResetActiveRunResult); ok {
			return x.ResetActiveRunResult
		}
	}
	return nil
}

func (x *Response) GetMoveActiveSplitBackResult() *MoveActiveSplitBackResult {
	if x != nil {
		if x, ok := x.Payload.(*Response_MoveActiveSplitBackResult); ok {
			return x.MoveActiveSplitBackResult
		}
	}
	return nil
}

type isResponse_Payload interface {
	isResponse_Payload()
}

type Response_AdvanceSplitResult struct {
	AdvanceSplitResult *AdvanceSplitResult `protobuf:"bytes,2,opt,name=advance_split_result,json=advanceSplitResult,proto3,oneof"`
}

type Response_ResetActiveRunResult struct {
	ResetActiveRunResult *ResetActiveRunResult `protobuf:"bytes,3,opt,name=reset_active_run_result,json=resetActiveRunResult,proto3,oneof"`
}

type Response_MoveActiveSplitBackResult struct {
	MoveActiveSplitBackResult *MoveActiveSplitBackResult `protobuf:"bytes,4,opt,name=move_active_split_back_result,json=moveActiveSplitBackResult,proto3,oneof"`
}

func (*Response_AdvanceSplitResult) isResponse_Payload() {}

func (*Response_ResetActiveRunResult) isResponse_Payload() {}

func (*Response_MoveActiveSplitBackResult) isResponse_Payload() {}

type AdvanceSplit struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunId          int64                  `protobuf:"varint,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ActiveSplitIdx int64                  `protobuf:"varint,2,opt,name=active_split_idx,json=activeSplitIdx,proto3" json:"active_split_idx,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdvanceSplit) Reset() {
	*x = AdvanceSplit{}
	mi := &file_pkg_ipc_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvanceSplit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvanceSplit) ProtoMessage() {}

func (x *AdvanceSplit) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvanceSplit.ProtoReflect.Descriptor instead.
func (*AdvanceSplit) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_message_proto_rawDescGZIP(), []int{2}
}

func (x *AdvanceSplit) GetRunId() int64 {
	if x != nil {
		return x.RunId
	}
	return 0
}

func (x *AdvanceSplit) GetActiveSplitIdx() int64 {
	if x != nil {
		return x.ActiveSplitIdx
	}
	return 0
}

type ResetActiveRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         int64                  `protobuf:"varint,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetActiveRun) Reset() {
	*x = ResetActiveRun{}
	mi := &file_pkg_ipc_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetActiveRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetActiveRun) ProtoMessage() {}

func (x *ResetActiveRun) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetActiveRun.ProtoReflect.Descriptor instead.
func (*ResetActiveRun) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_message_proto_rawDescGZIP(), []int{3}
}

func (x *ResetActiveRun) GetRunId() int64 {
	if x != nil {
		return x.RunId
	}
	return 0
}

type MoveActiveSplitBack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         int64                  `protobuf:"varint,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveActiveSplitBack) Reset() {
	*x = MoveActiveSplitBack{}
	mi := &file_pkg_ipc_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveActiveSplitBack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveActiveSplitBack) ProtoMessage() {}

func (x *MoveActiveSplitBack) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveActiveSplitBack.ProtoReflect.Descriptor instead.
func (*MoveActiveSplitBack) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_message_proto_rawDescGZIP(), []int{4}
}

func (x *MoveActiveSplitBack) GetRunId() int64 {
	if x != nil {
		return x.RunId
	}
	return 0
}

type AdvanceSplitResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunId          int64                  `protobuf:"varint,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ActiveSplitIdx int64                  `protobuf:"varint,2,opt,name=active_split_idx,json=activeSplitIdx,proto3" json:"active_split_idx,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdvanceSplitResult) Reset() {
	*x = AdvanceSplitResult{}
	mi := &file_pkg_ipc_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvanceSplitResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvanceSplitResult) ProtoMessage() {}

func (x *AdvanceSplitResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvanceSplitResult.ProtoReflect.Descriptor instead.
func (*AdvanceSplitResult) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_message_proto_rawDescGZIP(), []int{5}
}

func (x *AdvanceSplitResult) GetRunId() int64 {
	if x != nil {
		return x.RunId
	}
	return 0
}

func (x *AdvanceSplitResult) GetActiveSplitIdx() int64 {
	if x != nil {
		return x.ActiveSplitIdx
	}
	return 0
}

type ResetActiveRunResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         int64                  `protobuf:"varint,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetActiveRunResult) Reset() {
	*x = ResetActiveRunResult{}
	mi := &file_pkg_ipc_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetActiveRunResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetActiveRunResult) ProtoMessage() {}

func (x *ResetActiveRunResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetActiveRunResult.ProtoReflect.Descriptor instead.
func (*ResetActiveRunResult) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_message_proto_rawDescGZIP(), []int{6}
}

func (x *ResetActiveRunResult) GetRunId() int64 {
	if x != nil {
		return x.RunId
	}
	return 0
}

type MoveActiveSplitBackResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         int64                  `protobuf:"varint,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveActiveSplitBackResult) Reset() {
	*x = MoveActiveSplitBackResult{}
	mi := &file_pkg_ipc_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveActiveSplitBackResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveActiveSplitBackResult) ProtoMessage() {}

func (x *MoveActiveSplitBackResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveActiveSplitBackResult.ProtoReflect.Descriptor instead.
func (*MoveActiveSplitBackResult) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_message_proto_rawDescGZIP(), []int{7}
}

func (x *MoveActiveSplitBackResult) GetRunId() int64 {
	if x != nil {
		return x.RunId
	}
	return 0
}

var File_pkg_ipc_message_proto protoreflect.FileDescriptor

const file_pkg_ipc_message_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/ipc/message.proto\x12\x03ipc\"\xf0\x01\n" +
	"\aRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\radvance_split\x18\x02 \x01(\v2\x11.ipc.AdvanceSplitH\x00R\fadvanceSplit\x12?\n" +
	"\x10reset_active_run\x18\x03 \x01(\v2\x13.ipc.ResetActiveRunH\x00R\x0eresetActiveRun\x12O\n" +
	"\x16move_active_split_back\x18\x04 \x01(\v2\x18.ipc.MoveActiveSplitBackH\x00R\x13moveActiveSplitBackB\t\n" +
	"\apayload\"\xaa\x02\n" +
	"\bResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12K\n" +
	"\x14advance_split_result\x18\x02 \x01(\v2\x17.ipc.AdvanceSplitResultH\x00R\x12advanceSplitResult\x12R\n" +
	"\x17reset_active_run_result\x18\x03 \x01(\v2\x19.ipc.ResetActiveRunResultH\x00R\x14resetActiveRunResult\x12b\n" +
	"\x1dmove_active_split_back_result\x18\x04 \x01(\v2\x1e.ipc.MoveActiveSplitBackResultH\x00R\x19moveActiveSplitBackResultB\t\n" +
	"\apayload\"O\n" +
	"\fAdvanceSplit\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\x03R\x05runId\x12(\n" +
	"\x10active_split_idx\x18\x02 \x01(\x03R\x0eactiveSplitIdx\"'\n" +
	"\x0eResetActiveRun\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\x03R\x05runId\",\n" +
	"\x13MoveActiveSplitBack\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\x03R\x05runId\"U\n" +
	"\x12AdvanceSplitResult\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\x03R\x05runId\x12(\n" +
	"\x10active_split_idx\x18\x02 \x01(\x03R\x0eactiveSplitIdx\"-\n" +
	"\x14ResetActiveRunResult\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\x03R\x05runId\"2\n" +
	"\x19MoveActiveSplitBackResult\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\x03R\x05runId23\n" +
	"\x03IPC\x12,\n" +
	"\rHandleRequest\x12\f.ipc.Request\x1a\r.ipc.ResponseB#Z!codeberg.org/veya/ermokie/pkg/ipcb\x06proto3"

var (
	file_pkg_ipc_message_proto_rawDescOnce sync.Once
	file_pkg_ipc_message_proto_rawDescData []byte
)

func file_pkg_ipc_message_proto_rawDescGZIP() []byte {
	file_pkg_ipc_message_proto_rawDescOnce.Do(func() {
		file_pkg_ipc_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_ipc_message_proto_rawDesc), len(file_pkg_ipc_message_proto_rawDesc)))
	})
	return file_pkg_ipc_message_proto_rawDescData
}

var file_pkg_ipc_message_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_ipc_message_proto_goTypes = []any{
	(*Request)(nil),                   // 0: ipc.Request
	(*Response)(nil),                  // 1: ipc.Response
	(*AdvanceSplit)(nil),              // 2: ipc.AdvanceSplit
	(*ResetActiveRun)(nil),            // 3: ipc.ResetActiveRun
	(*MoveActiveSplitBack)(nil),       // 4: ipc.MoveActiveSplitBack
	(*AdvanceSplitResult)(nil),        // 5: ipc.AdvanceSplitResult
	(*ResetActiveRunResult)(nil),      // 6: ipc.ResetActiveRunResult
	(*MoveActiveSplitBackResult)(nil), // 7: ipc.MoveActiveSplitBackResult
}
var file_pkg_ipc_message_proto_depIdxs = []int32{
	2, // 0: ipc.Request.advance_split:type_name -> ipc.AdvanceSplit
	3, // 1: ipc.Request.reset_active_run:type_name -> ipc.ResetActiveRun
	4, // 2: ipc.Request.move_active_split_back:type_name -> ipc.MoveActiveSplitBack
	5, // 3: ipc.Response.advance_split_result:type_name -> ipc.AdvanceSplitResult
	6, // 4: ipc.Response.reset_active_run_result:type_name -> ipc.ResetActiveRunResult
	7, // 5: ipc.Response.move_active_split_back_result:type_name -> ipc.MoveActiveSplitBackResult
	0, // 6: ipc.IPC.HandleRequest:input_type -> ipc.Request
	1, // 7: ipc.IPC.HandleRequest:output_type -> ipc.Response
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_ipc_message_proto_init() }
func file_pkg_ipc_message_proto_init() {
	if File_pkg_ipc_message_proto != nil {
		return
	}
	file_pkg_ipc_message_proto_msgTypes[0].OneofWrappers = []any{
		(*Request_AdvanceSplit)(nil),
		(*Request_ResetActiveRun)(nil),
		(*Request_MoveActiveSplitBack)(nil),
	}
	file_pkg_ipc_message_proto_msgTypes[1].OneofWrappers = []any{
		(*Response_AdvanceSplitResult)(nil),
		(*Response_ResetActiveRunResult)(nil),
		(*Response_MoveActiveSplitBackResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_ipc_message_proto_rawDesc), len(file_pkg_ipc_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_ipc_message_proto_goTypes,
		DependencyIndexes: file_pkg_ipc_message_proto_depIdxs,
		MessageInfos:      file_pkg_ipc_message_proto_msgTypes,
	}.Build()
	File_pkg_ipc_message_proto = out.File
	file_pkg_ipc_message_proto_goTypes = nil
	file_pkg_ipc_message_proto_depIdxs = nil
}
