// Code generated by protoc-gen-go-drpc. DO NOT EDIT.
// protoc-gen-go-drpc version: v0.0.34
// source: pkg/ipc/message.proto

package ipc

import (
	context "context"
	errors "errors"
	protojson "google.golang.org/protobuf/encoding/protojson"
	proto "google.golang.org/protobuf/proto"
	drpc "storj.io/drpc"
	drpcerr "storj.io/drpc/drpcerr"
)

type drpcEncoding_File_pkg_ipc_message_proto struct{}

func (drpcEncoding_File_pkg_ipc_message_proto) Marshal(msg drpc.Message) ([]byte, error) {
	return proto.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_pkg_ipc_message_proto) MarshalAppend(buf []byte, msg drpc.Message) ([]byte, error) {
	return proto.MarshalOptions{}.MarshalAppend(buf, msg.(proto.Message))
}

func (drpcEncoding_File_pkg_ipc_message_proto) Unmarshal(buf []byte, msg drpc.Message) error {
	return proto.Unmarshal(buf, msg.(proto.Message))
}

func (drpcEncoding_File_pkg_ipc_message_proto) JSONMarshal(msg drpc.Message) ([]byte, error) {
	return protojson.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_pkg_ipc_message_proto) JSONUnmarshal(buf []byte, msg drpc.Message) error {
	return protojson.Unmarshal(buf, msg.(proto.Message))
}

type DRPCIPCClient interface {
	DRPCConn() drpc.Conn

	HandleRequest(ctx context.Context, in *Request) (*Response, error)
}

type drpcIPCClient struct {
	cc drpc.Conn
}

func NewDRPCIPCClient(cc drpc.Conn) DRPCIPCClient {
	return &drpcIPCClient{cc}
}

func (c *drpcIPCClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcIPCClient) HandleRequest(ctx context.Context, in *Request) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ipc.IPC/HandleRequest", drpcEncoding_File_pkg_ipc_message_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type DRPCIPCServer interface {
	HandleRequest(context.Context, *Request) (*Response, error)
}

type DRPCIPCUnimplementedServer struct{}

func (s *DRPCIPCUnimplementedServer) HandleRequest(context.Context, *Request) (*Response, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

type DRPCIPCDescription struct{}

func (DRPCIPCDescription) NumMethods() int { return 1 }

func (DRPCIPCDescription) Method(n int) (string, drpc.Encoding, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/ipc.IPC/HandleRequest", drpcEncoding_File_pkg_ipc_message_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCIPCServer).
					HandleRequest(
						ctx,
						in1.(*Request),
					)
			}, DRPCIPCServer.HandleRequest, true
	default:
		return "", nil, nil, nil, false
	}
}

func DRPCRegisterIPC(mux drpc.Mux, impl DRPCIPCServer) error {
	return mux.Register(impl, DRPCIPCDescription{})
}

type DRPCIPC_HandleRequestStream interface {
	drpc.Stream
	SendAndClose(*Response) error
}

type drpcIPC_HandleRequestStream struct {
	drpc.Stream
}

func (x *drpcIPC_HandleRequestStream) SendAndClose(m *Response) error {
	if err := x.MsgSend(m, drpcEncoding_File_pkg_ipc_message_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}
