// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: broker.sql

package sqlc

import (
	"context"
)

const deleteOldMessageLogs = `-- name: DeleteOldMessageLogs :exec
DELETE FROM message_log
WHERE created_at < datetime('now', ?)
`

func (q *Queries) DeleteOldMessageLogs(ctx context.Context, datetime interface{}) error {
	_, err := q.db.ExecContext(ctx, deleteOldMessageLogs, datetime)
	return err
}

const deleteOldMessages = `-- name: DeleteOldMessages :exec

DELETE FROM message_queue
WHERE consumed_by IS NOT NULL
AND created_at < datetime('now', ?)
`

// - cleanup
func (q *Queries) DeleteOldMessages(ctx context.Context, datetime interface{}) error {
	_, err := q.db.ExecContext(ctx, deleteOldMessages, datetime)
	return err
}

const deleteOldSubscriptions = `-- name: DeleteOldSubscriptions :exec
DELETE FROM subscriptions
WHERE timestamp < datetime('now', ?)
`

func (q *Queries) DeleteOldSubscriptions(ctx context.Context, datetime interface{}) error {
	_, err := q.db.ExecContext(ctx, deleteOldSubscriptions, datetime)
	return err
}

const deleteOldUnconsumedMessages = `-- name: DeleteOldUnconsumedMessages :exec
DELETE FROM message_queue
WHERE consumed_by IS NULL
AND created_at < datetime('now', ?)
`

func (q *Queries) DeleteOldUnconsumedMessages(ctx context.Context, datetime interface{}) error {
	_, err := q.db.ExecContext(ctx, deleteOldUnconsumedMessages, datetime)
	return err
}

const deleteSubscriptionsByTopic = `-- name: DeleteSubscriptionsByTopic :exec
DELETE FROM subscriptions
WHERE topic = ?
`

func (q *Queries) DeleteSubscriptionsByTopic(ctx context.Context, topic string) error {
	_, err := q.db.ExecContext(ctx, deleteSubscriptionsByTopic, topic)
	return err
}
