// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inserts.sql

package sqlc

import (
	"context"
	"database/sql"
)

const insertRun = `-- name: InsertRun :one
INSERT INTO runs (name, attempts, active_split, game, category) VALUES (?, ?, ?, ?, ?) RETURNING id
`

type InsertRunParams struct {
	Name        string
	Attempts    sql.NullInt64
	ActiveSplit sql.NullInt64
	Game        sql.NullString
	Category    sql.NullString
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertRun,
		arg.Name,
		arg.Attempts,
		arg.ActiveSplit,
		arg.Game,
		arg.Category,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSplit = `-- name: InsertSplit :exec
INSERT INTO splits (run_id, name, hit_count, pb_hit_count, idx, save_file) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertSplitParams struct {
	RunID      int64
	Name       string
	HitCount   sql.NullInt64
	PbHitCount sql.NullInt64
	Idx        int64
	SaveFile   sql.NullString
}

func (q *Queries) InsertSplit(ctx context.Context, arg InsertSplitParams) error {
	_, err := q.db.ExecContext(ctx, insertSplit,
		arg.RunID,
		arg.Name,
		arg.HitCount,
		arg.PbHitCount,
		arg.Idx,
		arg.SaveFile,
	)
	return err
}
