// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type MessageLog struct {
	ID        int64
	MessageID int64
	Topic     string
	Action    string
	Consumer  sql.NullString
	CreatedAt interface{}
}

type MessageQueue struct {
	ID         int64
	Topic      string
	Payload    string
	CreatedAt  interface{}
	ConsumedBy sql.NullString
	ConsumedAt sql.NullTime
}

type MiscInfo struct {
	One       int64
	ActiveRun sql.NullInt64
}

type Run struct {
	ID          int64
	Name        string
	Attempts    sql.NullInt64
	ActiveSplit sql.NullInt64
	Game        sql.NullString
	Category    sql.NullString
}

type Split struct {
	ID         int64
	RunID      int64
	Name       string
	HitCount   sql.NullInt64
	PbHitCount sql.NullInt64
	Diff       sql.NullInt64
	Idx        int64
	SaveFile   sql.NullString
}

type Subscription struct {
	ID        int64
	MessageID int64
	Topic     string
	Action    string
	Consumer  sql.NullString
	Timestamp sql.NullTime
}
