// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: selects.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getActiveRun = `-- name: GetActiveRun :one
SELECT id, name, game, category, attempts, active_split
FROM runs r JOIN misc_info m ON m.active_run = r.id
`

type GetActiveRunRow struct {
	ID          int64
	Name        string
	Game        sql.NullString
	Category    sql.NullString
	Attempts    sql.NullInt64
	ActiveSplit sql.NullInt64
}

func (q *Queries) GetActiveRun(ctx context.Context) (GetActiveRunRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveRun)
	var i GetActiveRunRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Game,
		&i.Category,
		&i.Attempts,
		&i.ActiveSplit,
	)
	return i, err
}

const getAllRunNames = `-- name: GetAllRunNames :many
SELECT id, name FROM runs
`

type GetAllRunNamesRow struct {
	ID   int64
	Name string
}

func (q *Queries) GetAllRunNames(ctx context.Context) ([]GetAllRunNamesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllRunNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllRunNamesRow
	for rows.Next() {
		var i GetAllRunNamesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllRuns = `-- name: GetAllRuns :many
SELECT id, name, game, category, attempts, active_split FROM runs
`

type GetAllRunsRow struct {
	ID          int64
	Name        string
	Game        sql.NullString
	Category    sql.NullString
	Attempts    sql.NullInt64
	ActiveSplit sql.NullInt64
}

func (q *Queries) GetAllRuns(ctx context.Context) ([]GetAllRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllRunsRow
	for rows.Next() {
		var i GetAllRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Game,
			&i.Category,
			&i.Attempts,
			&i.ActiveSplit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRunAttemptsByName = `-- name: GetRunAttemptsByName :one
SELECT attempts FROM runs WHERE name = ?
`

func (q *Queries) GetRunAttemptsByName(ctx context.Context, name string) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, getRunAttemptsByName, name)
	var attempts sql.NullInt64
	err := row.Scan(&attempts)
	return attempts, err
}

const getRunByID = `-- name: GetRunByID :one
SELECT id, name, game, category, attempts, active_split FROM runs WHERE id = ?
`

type GetRunByIDRow struct {
	ID          int64
	Name        string
	Game        sql.NullString
	Category    sql.NullString
	Attempts    sql.NullInt64
	ActiveSplit sql.NullInt64
}

func (q *Queries) GetRunByID(ctx context.Context, id int64) (GetRunByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getRunByID, id)
	var i GetRunByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Game,
		&i.Category,
		&i.Attempts,
		&i.ActiveSplit,
	)
	return i, err
}

const getRunByName = `-- name: GetRunByName :one
SELECT id, name, game, category, attempts, active_split FROM runs WHERE name = ?
`

type GetRunByNameRow struct {
	ID          int64
	Name        string
	Game        sql.NullString
	Category    sql.NullString
	Attempts    sql.NullInt64
	ActiveSplit sql.NullInt64
}

func (q *Queries) GetRunByName(ctx context.Context, name string) (GetRunByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getRunByName, name)
	var i GetRunByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Game,
		&i.Category,
		&i.Attempts,
		&i.ActiveSplit,
	)
	return i, err
}

const getRunIDByName = `-- name: GetRunIDByName :one
SELECT id FROM runs WHERE name = ?
`

func (q *Queries) GetRunIDByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRunIDByName, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getSplitByID = `-- name: GetSplitByID :one
SELECT id, run_id, name, hit_count, pb_hit_count, diff, idx, save_file
FROM splits 
WHERE id = ?
`

func (q *Queries) GetSplitByID(ctx context.Context, id int64) (Split, error) {
	row := q.db.QueryRowContext(ctx, getSplitByID, id)
	var i Split
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.HitCount,
		&i.PbHitCount,
		&i.Diff,
		&i.Idx,
		&i.SaveFile,
	)
	return i, err
}

const getSplitByRunIDAndIdx = `-- name: GetSplitByRunIDAndIdx :one
SELECT id, run_id, name, hit_count, pb_hit_count, diff, idx, save_file 
FROM splits 
WHERE run_id = ? AND idx = ?
`

type GetSplitByRunIDAndIdxParams struct {
	RunID int64
	Idx   int64
}

func (q *Queries) GetSplitByRunIDAndIdx(ctx context.Context, arg GetSplitByRunIDAndIdxParams) (Split, error) {
	row := q.db.QueryRowContext(ctx, getSplitByRunIDAndIdx, arg.RunID, arg.Idx)
	var i Split
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.HitCount,
		&i.PbHitCount,
		&i.Diff,
		&i.Idx,
		&i.SaveFile,
	)
	return i, err
}

const getSplitByRunNameAndIdx = `-- name: GetSplitByRunNameAndIdx :one
SELECT s.id,
  s.run_id,
  s.name,
  s.hit_count,
  s.pb_hit_count,
  s.diff,
  s.idx,
  s.save_file
FROM splits s
JOIN runs r ON s.run_id = r.id
WHERE r.name = ? AND s.idx = ?
`

type GetSplitByRunNameAndIdxParams struct {
	Name string
	Idx  int64
}

func (q *Queries) GetSplitByRunNameAndIdx(ctx context.Context, arg GetSplitByRunNameAndIdxParams) (Split, error) {
	row := q.db.QueryRowContext(ctx, getSplitByRunNameAndIdx, arg.Name, arg.Idx)
	var i Split
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.HitCount,
		&i.PbHitCount,
		&i.Diff,
		&i.Idx,
		&i.SaveFile,
	)
	return i, err
}

const getSplitTotalsByRunID = `-- name: GetSplitTotalsByRunID :one
SELECT 
  SUM(hit_count) as total_hits,
  SUM(pb_hit_count) as total_pb,
  SUM(diff) as total_diff
FROM splits 
WHERE run_id = ?
`

type GetSplitTotalsByRunIDRow struct {
	TotalHits sql.NullFloat64
	TotalPb   sql.NullFloat64
	TotalDiff sql.NullFloat64
}

func (q *Queries) GetSplitTotalsByRunID(ctx context.Context, runID int64) (GetSplitTotalsByRunIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSplitTotalsByRunID, runID)
	var i GetSplitTotalsByRunIDRow
	err := row.Scan(&i.TotalHits, &i.TotalPb, &i.TotalDiff)
	return i, err
}

const getSplitsByRunID = `-- name: GetSplitsByRunID :many
SELECT
  s.id,
  s.run_id,
  s.name,
  s.hit_count,
  s.pb_hit_count,
  s.diff,
  s.idx,
  s.save_file,
  (s.idx = r.active_split) AS is_active
FROM
splits AS s
JOIN
runs AS r
ON r.id = s.run_id
WHERE
s.run_id = ?
ORDER BY
s.idx
`

type GetSplitsByRunIDRow struct {
	ID         int64
	RunID      int64
	Name       string
	HitCount   sql.NullInt64
	PbHitCount sql.NullInt64
	Diff       sql.NullInt64
	Idx        int64
	SaveFile   sql.NullString
	IsActive   interface{}
}

func (q *Queries) GetSplitsByRunID(ctx context.Context, runID int64) ([]GetSplitsByRunIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getSplitsByRunID, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSplitsByRunIDRow
	for rows.Next() {
		var i GetSplitsByRunIDRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Name,
			&i.HitCount,
			&i.PbHitCount,
			&i.Diff,
			&i.Idx,
			&i.SaveFile,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSplitsByRunName = `-- name: GetSplitsByRunName :many
SELECT
  s.id,
  s.run_id,
  s.name,
  s.hit_count,
  s.pb_hit_count,
  s.diff,
  s.idx,
  s.save_file,
  (s.idx = r.active_split) AS is_active
FROM
splits AS s
JOIN
runs AS r
ON r.id = s.run_id
WHERE
r.name = ?
ORDER BY
s.idx
`

type GetSplitsByRunNameRow struct {
	ID         int64
	RunID      int64
	Name       string
	HitCount   sql.NullInt64
	PbHitCount sql.NullInt64
	Diff       sql.NullInt64
	Idx        int64
	SaveFile   sql.NullString
	IsActive   interface{}
}

func (q *Queries) GetSplitsByRunName(ctx context.Context, name string) ([]GetSplitsByRunNameRow, error) {
	rows, err := q.db.QueryContext(ctx, getSplitsByRunName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSplitsByRunNameRow
	for rows.Next() {
		var i GetSplitsByRunNameRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Name,
			&i.HitCount,
			&i.PbHitCount,
			&i.Diff,
			&i.Idx,
			&i.SaveFile,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
