// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: updates.sql

package sqlc

import (
	"context"
	"database/sql"
)

const advanceSplitInActiveRun = `-- name: AdvanceSplitInActiveRun :exec
UPDATE runs
SET active_split = active_split + 1
WHERE id = (SELECT active_run FROM misc_info WHERE one = 1)
`

func (q *Queries) AdvanceSplitInActiveRun(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, advanceSplitInActiveRun)
	return err
}

const goBackSplitInActiveRun = `-- name: GoBackSplitInActiveRun :exec
UPDATE runs
SET active_split = MAX(active_split - 1, 0)
WHERE id = (SELECT active_run FROM misc_info WHERE one = 1)
`

func (q *Queries) GoBackSplitInActiveRun(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, goBackSplitInActiveRun)
	return err
}

const updateActiveRun = `-- name: UpdateActiveRun :exec
UPDATE misc_info
SET active_run = (
  SELECT id FROM runs WHERE name = ?
)
`

func (q *Queries) UpdateActiveRun(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, updateActiveRun, name)
	return err
}

const updateActiveRunByID = `-- name: UpdateActiveRunByID :exec
UPDATE misc_info
SET active_run = ?
`

func (q *Queries) UpdateActiveRunByID(ctx context.Context, activeRun sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, updateActiveRunByID, activeRun)
	return err
}

const updateActiveSplitByID = `-- name: UpdateActiveSplitByID :exec
UPDATE runs
SET active_split = (
  SELECT idx FROM splits WHERE splits.id = ?
)
WHERE runs.id = ?
`

type UpdateActiveSplitByIDParams struct {
	ID   int64
	ID_2 int64
}

func (q *Queries) UpdateActiveSplitByID(ctx context.Context, arg UpdateActiveSplitByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateActiveSplitByID, arg.ID, arg.ID_2)
	return err
}
