// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: updates.sql

package sqlc

import (
	"context"
	"database/sql"
)

const advanceSplitInActiveRun = `-- name: AdvanceSplitInActiveRun :exec
UPDATE runs
SET active_split = MIN(
  active_split + 1,
  COALESCE((SELECT MAX(idx) FROM splits WHERE run_id = runs.id), active_split)
)
WHERE id = (SELECT active_run FROM misc_info WHERE one = 1)
`

func (q *Queries) AdvanceSplitInActiveRun(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, advanceSplitInActiveRun)
	return err
}

const decrementActiveSplitHit = `-- name: DecrementActiveSplitHit :exec
UPDATE splits
SET hit_count = MAX(COALESCE(hit_count, 0) - 1, 0)
WHERE run_id = (SELECT active_run FROM misc_info WHERE one = 1)
  AND idx = (SELECT active_split FROM runs WHERE runs.id = splits.run_id)
`

func (q *Queries) DecrementActiveSplitHit(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, decrementActiveSplitHit)
	return err
}

const goBackSplitInActiveRun = `-- name: GoBackSplitInActiveRun :exec
UPDATE runs
SET active_split = MAX(active_split - 1, 0)
WHERE id = (SELECT active_run FROM misc_info WHERE one = 1)
`

func (q *Queries) GoBackSplitInActiveRun(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, goBackSplitInActiveRun)
	return err
}

const incrementActiveSplitHit = `-- name: IncrementActiveSplitHit :exec
UPDATE splits
SET hit_count = COALESCE(hit_count, 0) + 1
WHERE run_id = (SELECT active_run FROM misc_info WHERE one = 1)
  AND idx = (SELECT active_split FROM runs WHERE runs.id = splits.run_id)
`

func (q *Queries) IncrementActiveSplitHit(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, incrementActiveSplitHit)
	return err
}

const resetActiveRunHits = `-- name: ResetActiveRunHits :exec
UPDATE splits
SET hit_count = 0
WHERE run_id = (SELECT active_run FROM misc_info WHERE one = 1)
`

func (q *Queries) ResetActiveRunHits(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetActiveRunHits)
	return err
}

const resetActiveRunProgress = `-- name: ResetActiveRunProgress :exec
UPDATE runs
SET active_split = 0,
    attempts = COALESCE(attempts, 0) + 1
WHERE id = (SELECT active_run FROM misc_info WHERE one = 1)
`

func (q *Queries) ResetActiveRunProgress(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetActiveRunProgress)
	return err
}

const updateActiveRun = `-- name: UpdateActiveRun :exec
UPDATE misc_info
SET active_run = (
  SELECT id FROM runs WHERE name = ?
)
`

func (q *Queries) UpdateActiveRun(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, updateActiveRun, name)
	return err
}

const updateActiveRunByID = `-- name: UpdateActiveRunByID :exec
UPDATE misc_info
SET active_run = ?
`

func (q *Queries) UpdateActiveRunByID(ctx context.Context, activeRun sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, updateActiveRunByID, activeRun)
	return err
}

const updateActiveSplitByID = `-- name: UpdateActiveSplitByID :exec
UPDATE runs
SET active_split = (
  SELECT idx FROM splits WHERE splits.id = ?
)
WHERE runs.id = ?
`

type UpdateActiveSplitByIDParams struct {
	ID   int64
	ID_2 int64
}

func (q *Queries) UpdateActiveSplitByID(ctx context.Context, arg UpdateActiveSplitByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateActiveSplitByID, arg.ID, arg.ID_2)
	return err
}
